"""add academic eligibility

Revision ID: 084230ad1326
Revises: edd04eeda927
Create Date: 2026-07-04 11:59:36.771701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '084230ad1326'
down_revision: Union[str, Sequence[str], None] = 'edd04eeda927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester_profile', sa.Column('student_groups', sqlite.JSON(), server_default='[]', nullable=False))
    op.add_column('timetable_slot', sa.Column('required_groups', sqlite.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_slot', 'required_groups')
    op.drop_column('semester_profile', 'student_groups')
    # ### end Alembic commands ###
