"""Add ImportSession model

Revision ID: 61061c0cd768
Revises: b2c3d4e5f6a7
Create Date: 2026-07-05 18:07:42.870929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '61061c0cd768'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Enum('timetable', 'calendar', name='importtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'confirmed', 'discarded', name='importstatusenum'), nullable=False),
    sa.Column('extracted_payload', sqlite.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_session')
    # ### end Alembic commands ###
