"""Add file path and nullable semester_id

Revision ID: e9ea455e0d8f
Revises: 61061c0cd768
Create Date: 2026-07-05 18:20:04.778700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ea455e0d8f'
down_revision: Union[str, Sequence[str], None] = '61061c0cd768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_session', schema=None) as batch_op:
        batch_op.alter_column('semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_session', schema=None) as batch_op:
        batch_op.alter_column('semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
