"""init_schema

Revision ID: edd04eeda927
Revises: 
Create Date: 2026-07-04 09:08:17.051527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd04eeda927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_system_preset', sa.Boolean(), nullable=False),
    sa.Column('default_cancels_lectures', sa.Boolean(), nullable=False),
    sa.Column('default_counts_towards_attendance', sa.Boolean(), nullable=False),
    sa.Column('default_is_working_day', sa.Boolean(), nullable=False),
    sa.Column('default_exclude_from_recommendation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('semester_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('min_overall_percentage', sa.Float(), nullable=False),
    sa.Column('min_subject_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('custom_type_label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cancels_lectures_override', sa.Boolean(), nullable=True),
    sa.Column('counts_towards_attendance_override', sa.Boolean(), nullable=True),
    sa.Column('is_working_day_override', sa.Boolean(), nullable=True),
    sa.Column('exclude_from_recommendation_override', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='check_event_dates'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type_definition.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('min_percentage_override', sa.Float(), nullable=True),
    sa.Column('held_count', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('held_count >= 0', name='check_held_positive'),
    sa.CheckConstraint('present_count <= held_count', name='check_present_lte_held'),
    sa.CheckConstraint('present_count >= 0', name='check_present_positive'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdayenum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_time_range'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_slot')
    op.drop_table('subject')
    op.drop_table('semester_event')
    op.drop_table('semester_profile')
    op.drop_table('event_type_definition')
    # ### end Alembic commands ###
